name: Receiver Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install coverage tool
      run: |
        sudo apt-get update
        sudo apt-get install -y gcovr
        
    - name: Software build for Testing
      run:Â gcc -Wall -Wextra -fprofile-arcs -ftest-coverage -o bmsReceiver Receiver/*.c* 
    - name: run
      run: ./testchecker

    - name: collect coverage
      run: gcovr --gcov-exclude=".*test.*" -r . --html --html-details -o coverage.html

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: ./*.html
        retention-days: 1
        
    - name: Software build for production
      run: g++ -I ./Receiver/production/ -Wall -Wextra -o bmsReceiver Receiver/*.c*
      
    - name: bmsReceiver production
      run: ./bmsReceiver 
